config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from shop.views import *


urlpatterns = [
    path('', index, name='index'),
   
]

shop/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    name = models.CharField(max_length=250)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE, null=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField()
    price = models.IntegerField(null=True)

    def __str__(self):
        return self.title

shop/views.py
from django.shortcuts import render
from .models import *


# Create your views here.

def index(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    categoryId = request.GET.get('category')
    products = products.filter(sub_category=categoryId) if categoryId else products
    context = {
        'categories': categories,
        'products': products
    }
    return render(request, 'index.html', context)

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Home | E-Shopper</title>
	<link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/main.css' %}" rel="stylesheet">
</head>

<body>
	<div class="header-middle">
		<div class="container">
			<div class="row">
				<div class="col-sm-4">
					<div class="logo pull-left">
						<a href="/" style="font-size: 28px;">
							My E-Shop
						</a>
					</div>
				</div>
				<div class="col-sm-8">
					<div class="shop-menu pull-right">
						<ul class="nav navbar-nav">
							<li><a href=""><i class="fa fa-crosshairs"></i> Checkout</a></li>
							<li><a href=""><i class="fa fa-shopping-cart"></i> Cart</a></li>
							<li><a href=""><i class="fa fa-lock"></i> Login</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						{% for category in categories %}
						<div class="panel-group category-products" id="accordian">
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{category.id}}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{category.name}}
										</a>
									</h4>
								</div>
								<div id="{{category.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											{% for i in category.subcategory_set.all %}
											<li><a href="/?category={{i.id}}">{{i.name}}</a></li>
											{% endfor %}
										</ul>
									</div>
								</div>
							</div>

						</div>
						{% endfor %}
					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items">
						<h2 class="title text-center">Products</h2>
						{% for product in products%}
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div>
									<div class="productinfo text-center">
										<img src="{{product.image.url}}" alt="" />
										<h2>${{product.price}}</h2>
										<p>{{product.title}}</p>
										<a href="#" class="btn btn-default add-to-cart"><i
												class="fa fa-shopping-cart"></i>Add to cart</a>
									</div>
								</div>
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
	<script src="{% static 'js/price-range.js' %}"></script>

</body>
</html>